### ISSUE TITLE
About React-Monaco-Editor support issues

### ISSUE THREAD

**Issue by resetsix** [DTStack/monaco-sql-languages#108]
Does Monaco SQL Languages support integration in React-Monaco-Editor?

**Comment by HaydenOrz** [comment]
> Does Monaco SQL Languages support integration in React-Monaco-Editor?

在功能上，Monaco SQL Languages 不会与 React-Monaco-Editor有冲突，唯一需要关心的是所依赖的 Monaco Editor 版本问题。我做了一些简单的尝试，目前看起来 Monaco SQL Languages 与 React-Monaco-Editor 的最新版本可以一起正常运行。
需要注意的是，我们并没有在不同版本的 Monaco Editor 上做充分的集成测试，目前 Monaco SQL Languages 所有的测试都基于  Monaco Editor 的 0.31.x 版本

**Comment by resetsix** [comment]
> > Does Monaco SQL Languages support integration in React-Monaco-Editor?
> 
> 在功能上，Monaco SQL Languages 不会与 React-Monaco-Editor有冲突，唯一需要关心的是所依赖的 Monaco Editor 版本问题。我做了一些简单的尝试，目前看起来 Monaco SQL Languages 与 React-Monaco-Editor 的最新版本可以一起正常运行。 需要注意的是，我们并没有在不同版本的 Monaco Editor 上做充分的集成测试，目前 Monaco SQL Languages 所有的测试都基于 Monaco Editor 的 0.31.x 版本

I see, thank u for your reply

**Comment by resetsix** [comment]
Sorry to bother you again,  [monaco-react](https://github.com/suren-atoyan/monaco-react) is an editor that does not require the use of webpack (or rollup / parcel / etc) profiles / plugins, and I don't know if this Monaco SQL Languages can be integrated with monaco-react. I tried but couldn't get it to work

**Comment by HaydenOrz** [comment]
> Sorry to bother you again, [monaco-react](https://github.com/suren-atoyan/monaco-react) is an editor that does not require the use of webpack (or rollup / parcel / etc) profiles / plugins, and I don't know if this Monaco SQL Languages can be integrated with monaco-react. I tried but couldn't get it to work.

我不确定你没有集成成功是否是因为[集成文档](https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.zh-CN.md)对你造成了困扰。

Monaco SQL Languages 也不依赖任何的 bundler，如果你的项目中没有用到 webpack/vite 等bundler，那么你只需要
1. 引入语言的 contribution 文件
2.定义全局变量 `window.MonacoEnvironment.getWorker` 来让monaco 可以找到语言服务对应的 worker，[就像这样](https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.zh-CN.md#%E4%BD%BF%E7%94%A8-vite)
3. setupLanguageFeatures 

就好了，实际上在 vite 中使用的和在无 bundler 环境中使用并没有太大的区别。  

另外，如果你需要的话，你可以提供一个最小化的demo，我可以在这个demo的基础上帮你完成 Monaco SQL Languages 的集成。

**Comment by resetsix** [comment]
> > Sorry to bother you again, [monaco-react](https://github.com/suren-atoyan/monaco-react) is an editor that does not require the use of webpack (or rollup / parcel / etc) profiles / plugins, and I don't know if this Monaco SQL Languages can be integrated with monaco-react. I tried but couldn't get it to work.
> 
> 我不确定你没有集成成功是否是因为[集成文档](https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.zh-CN.md)对你造成了困扰。
> 
> Monaco SQL Languages 也不依赖任何的 bundler，如果你的项目中没有用到 webpack/vite 等bundler，那么你只需要
> 
>     1. 引入语言的 contribution 文件
> 
>     2. 定义全局变量 `window.MonacoEnvironment.getWorker` 来让monaco 可以找到语言服务对应的 worker，[就像这样](https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.zh-CN.md#%E4%BD%BF%E7%94%A8-vite)
> 
>     3. setupLanguageFeatures
> 
> 
> 就好了，实际上在 vite 中使用的和在无 bundler 环境中使用并没有太大的区别。
> 
> 另外，如果你需要的话，你可以提供一个最小化的demo，我可以在这个demo的基础上帮你完成 Monaco SQL Languages 的集成。

This is a minimized [demo](https://github.com/resetsix/react-monaco-sql-language-demo) created by CRA and you are welcome to submit a PR.

What's bugging me is that I don't know where I should integrate `Monaco SQL Languages` when `monaco-editor` doesn't require webpack configuration.

**Comment by HaydenOrz** [comment]
> This is a minimized [demo](https://github.com/resetsix/react-monaco-sql-language-demo) created by CRA and you are welcome to submit a PR.
> 
> What's bugging me is that I don't know where I should integrate `Monaco SQL Languages` when `monaco-editor` doesn't require webpack configuration.

现在我明白你的问题了，这实际上不是 Monaco SQL Languages 的问题，也同样与 monaco-react 无关。

Monaco SQL Languages 提供的 language 的集成方式与 Monaco Editor 内置的 language 的集成方式完全相同。
 
主要问题在于，无论是 Monaco SQL Languages 提供的 language 还是 monaco editor 内置的 TypeScript 、JSON 等需要语法解析的 language，这些language的语法解析都在 web worker 中运行，以避免阻塞页面渲染，所以在使用这些language 之前，需要在全局定义 `window.MonacoEnvironment.getWorker` 或者 `window.MonacoEnvironment.getWorkerURL` 来让 monaco-editor 知道语言对应的 worker 文件在什么位置。
 
如果需要在一个CRA创建的项目中集成Monaco 相关的 languages，那么你必须修改一些打包配置，来让 worker 文件可以顺利的被 monaco 获取到，目前我所知的唯一的方式是在 CRA 项目中 运行 `npx eject` 来释放出 webpack 配置文件，除此之外，没有其他方法。

**Comment by resetsix** [comment]
Thanks for the reply, but I'm cracking up, I've been trying all afternoon to successfully integrate `Monaco SQL Languages` in monaco-react
I extended the webpack configuration for `CRA` via `craco`, but it didn't work (or maybe I misconfigured it)

The `Editor` component has an `onMount` property that gets the editor instance method, and I'm not sure where the entry point for registering custom languages with `monaco-react` is, but I didn't succeed in implementing keyword prompts for SQL Languages either

I think my mistake is in not knowing how to let `monaco-reac`t know what the corresponding work file is in question

Can you help me to solve this problem publicly? Thank you for your help

This is my test [code](https://github.com/resetsix/react-monaco-sql-language-demo.git)

**Comment by resetsix** [comment]
我哭死终于解决了`@monaco-editor/react`集成 `Monaco SQL Language` 不生效的问题了。

我先讲下都是基于`monacl-editor`二次封装的两个 `React` 编辑器各自区别：`react-monaco-editor`和`@monaco-editor/react`。
1. `react-monaco-editor`:
 - 这是较早的一个项目，社区驱动，由第三方维护。
 - 它提供了一套 `React` 组件，使得在 `React` 应用中集成 `Monaco Editor`变得简单。
 - 可能不会包含 `Monaco Editor` 最新版本的所有特性，依赖于社区的更新频率。
2. `@monaco-editor/react`:
- 这是一个较新的包，由微软的 `Monaco Editor` 团队或与其紧密合作的开发者维护。
- 它旨在提供更简单、更官方的方式将 `Monaco Editor` 集成到 `React` 应用中。
- 通常与 `Monaco Editor` 的最新版本保持同步更新，确保能够使用 `Monaco Editor` 的最新特性和改进。

> 最直观的区别是前者需要配置构建工具（如 `webpack`、`vite` 等），而后者是零配置。

以下示例使用[@craco/craco](https://github.com/dilanx/craco)工具拓展 `CRA` 脚手架的 `webpack` 配置，并能正常集成`Monaco SQl Language` 的 `craco.config.js` 配置代码与示例：

// craco.config.js (与 src 同级)
```js
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const webpack = require("webpack");
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const process = require("process");

const monacoWebpackPlugin = new MonacoWebpackPlugin({
    // features: [],
    // languages: [],
    customLanguages: [
        {
            label: "mysql",
            entry: "monaco-sql-languages/out/esm/mysql/mysql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/mysql/mySQLWorker",
                entry: "monaco-sql-languages/out/esm/mysql/mysql.worker",
            },
        },
        {
            label: "flinksql",
            entry: "monaco-sql-languages/out/esm/flinksql/flinksql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/flinksql/flinkSQLWorker",
                entry: "monaco-sql-languages/out/esm/flinksql/flinksql.worker",
            },
        },
        {
            label: "sparksql",
            entry: "monaco-sql-languages/out/esm/sparksql/sparksql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/sparksql/sparkSQLWorker",
                entry: "monaco-sql-languages/out/esm/sparksql/sparksql.worker",
            },
        },
        {
            label: "hivesql",
            entry: "monaco-sql-languages/out/esm/hivesql/hivesql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/hivesql/hiveSQLWorker",
                entry: "monaco-sql-languages/out/esm/hivesql/hivesql.worker",
            },
        },
        {
            label: "trinosql",
            entry: "monaco-sql-languages/out/esm/trinosql/trinosql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/trinosql/TrinoSQLWorker",
                entry: "monaco-sql-languages/out/esm/trinosql/trinosql.worker",
            },
        },
        {
            label: "pgsql",
            entry: "monaco-sql-languages/out/esm/pgsql/pgsql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/pgsql/PgSQLWorker",
                entry: "monaco-sql-languages/out/esm/pgsql/pgsql.worker",
            },
        },
        {
            label: "impalasql",
            entry: "monaco-sql-languages/out/esm/impalasql/impalasql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/impalasql/impalaSQLWorker",
                entry: "monaco-sql-languages/out/esm/impalasql/impalasql.worker",
            },
        },
    ],
});

// eslint-disable-next-line no-undef
module.exports = {
    webpack: {
        plugins: [
            new webpack.DefinePlugin({
                "process.env.NODE_DEBUG": process.env.NODE_DEBUG,
            }),
            monacoWebpackPlugin,
        ],
    },
};
```

- `@monaco-editor/react`使用方式如下

>  一定需要加上 `loader.config({ monaco });`我就是因为卡在这里，始终集成不了 Monaco SQL Language。

src/App.tsx

```tsx
import Editor, { loader } from "@monaco-editor/react";
import * as monaco from "monaco-editor";

// 导入monaco-editor的语言支持
loader.config({ monaco });

function App() {
    return <Editor height={600} language="mysql" theme="vs-dark" />;
}

export default App;
```

- `react-monaco-editor`使用方式如下

src/App.tsx

```tsx
import MonacoEditor from "react-monaco-editor";

function App() {
    return <MonacoEditor height={600} language="mysql" theme="vs-dark" />;
}

export default App;
```

- 两者效果皆相同
<img width="564" alt="图片" src="https://github.com/DTStack/monaco-sql-languages/assets/85431995/06dc50b8-5e57-4b50-8fbf-8e4a757d891d">

**Comment by HaydenOrz** [comment]
@resetsix 

我昨天也尝试了在你的demo中使用 craco 添加插件配置，但是启动后浏览器报错：

![image](https://github.com/DTStack/monaco-sql-languages/assets/58289241/4e320339-5512-4d36-9295-e9a27a770598)

不知道是哪里出了问题，我的 craco 配置是：
```js
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");

module.exports = {
  webpack: {
    plugins: {
      add: [
        new MonacoWebpackPlugin({
          features: [],
          languages: [],
          customLanguages: [
            {
              label: "mysql",
              entry: "monaco-sql-languages/out/esm/mysql/mysql.contribution",
              worker: {
                id: "monaco-sql-languages/out/esm/mysql/mySQLWorker",
                entry: "monaco-sql-languages/out/esm/mysql/mysql.worker",
              },
            },
          ],
        }),
      ],
    },
  },
};


```

**Comment by resetsix** [comment]
> @resetsix
> 
> 我昨天也尝试了在你的demo中使用 craco 添加插件配置，但是启动后浏览器报错：
> 
> ![image](https://private-user-images.githubusercontent.com/58289241/314902487-4e320339-5512-4d36-9295-e9a27a770598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODYyNzYsIm5iZiI6MTcxMDk4NTk3NiwicGF0aCI6Ii81ODI4OTI0MS8zMTQ5MDI0ODctNGUzMjAzMzktNTUxMi00ZDM2LTkyOTUtZTlhMjdhNzcwNTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAxNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTQ2ZDRlODEwNjVhNDU1M2RjNjg3NjJiYzZmOGIzZGUzYWJhOWM2MmM3ZWZlZDZhNGY4N2UwMTgxZWU2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pz4zarAcJJJ66QuuePc25usaIUXuzNsN9-d4Yzqy8Fk)
> 
> 不知道是哪里出了问题，我的 craco 配置是：
> 
> ```js
> const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
> 
> module.exports = {
>   webpack: {
>     plugins: {
>       add: [
>         new MonacoWebpackPlugin({
>           features: [],
>           languages: [],
>           customLanguages: [
>             {
>               label: "mysql",
>               entry: "monaco-sql-languages/out/esm/mysql/mysql.contribution",
>               worker: {
>                 id: "monaco-sql-languages/out/esm/mysql/mySQLWorker",
>                 entry: "monaco-sql-languages/out/esm/mysql/mysql.worker",
>               },
>             },
>           ],
>         }),
>       ],
>     },
>   },
> };
> ```

应该不需要`add`，你试一下这样呢
```js
plugins: [
	new webpack.DefinePlugin({
	"process.env.NODE_DEBUG": process.env.NODE_DEBUG,
}),
	// ...
],
```

**Comment by HaydenOrz** [comment]
@resetsix  

我重新装了一下依赖就没有这个问题了，很奇怪，总之是解决问题了哈！

**Comment by resetsix** [comment]
> @resetsix
> 
> 我重新装了一下依赖就没有这个问题了，很奇怪，总之是解决问题了哈！

好的。
