### ISSUE TITLE
How to adjust suggest filter

### ISSUE THREAD

**Issue by avysotskiy-sc** [DTStack/monaco-sql-languages#109]
Currently, suggestions are being shown depends on symbols.

![image](https://github.com/DTStack/monaco-sql-languages/assets/108337218/7b163a0d-546e-44a5-9ec4-b75175b402c8)

How to show suggestions depends on subword.

In my example showing only first 3 items:

![image](https://github.com/DTStack/monaco-sql-languages/assets/108337218/eac67272-b131-4618-a0c9-238ee5ae6c2c)

**Comment by HaydenOrz** [comment]
@avysotskiy-sc 

As far as I know, at the moment Monaco doesn't provide any options that can be used to adjust it. 

So you can only filter in completionService / provideCompletionItems:

```js
completionService: (model, position) => {
        const word = model.getWordUntilPosition(position);
        const wordText = word.word; // Get the word before the cursor
        const filteredCompletions = completions.filter(function(item) {
            return item.label.includes(word.word);
        });
}
```

**Comment by HaydenOrz** [comment]
Closed because this is inactive
