### ISSUE TITLE
Table alias not showing up in entities

### ISSUE THREAD

**Issue by simonflick** [DTStack/monaco-sql-languages#127]
I have created a `CompletionService` to autocomplete table column names. The `entities` object is very helpful for that. But it doesn't contain table aliases. Is this a planned feature?

**Comment by Cythia828** [comment]
> I have created a `CompletionService` to autocomplete table column names. The `entities` object is very helpful for that. But it doesn't contain table aliases. Is this a planned feature?

Thank you for your feedback. Table aliases' collecting is in our recent plans. Please wait for our new version.

**Comment by simonflick** [comment]
> Thank you for your feedback. Table aliases' collecting is in our recent plans. Please wait for our new version.

Awesome! Thanks for the great work.
