### ISSUE TITLE
Is there is a workaround to get auto complete feature?

### ISSUE THREAD

**Issue by DevAhmedAlayyat** [DTStack/monaco-sql-languages#13]
Is there is a workaround to get auto complete feature?

**Comment by wewoor** [comment]
Hi, @DevAhmedAlayyat we have supported the basic auto complete at the latest version, but now only support FlinkSQL langauge, you can refer to this project 

https://github.com/DTStack/dt-sql-parser/blob/main/src/parser/common/basicParser.ts

Preview: https://dtstack.github.io/monaco-sql-languages/
