### ISSUE TITLE
mococo-sql-languages 中的 website 无法正常运行

### ISSUE THREAD

**Issue by ImprovementSugar** [DTStack/monaco-sql-languages#131]
我按照官网的方式进行本地dev，执行如下命令
## Dev: cheat sheet

-   initial setup

    ```bash
    pnpm install
    ```

-   open the dev web

    ```bash
    pnpm watch-esm
    cd website
    pnpm install
    pnpm dev
    ```
    
   页面能够发正常访问，但是编辑SQL的时候出现  Error: Maximum call stack size exceeded 报错
   我的 pnpm 版本为 9.0.6 ，node版本是 18.20.3
   
![image](https://github.com/DTStack/monaco-sql-languages/assets/47029292/86e80cf1-a1a8-401c-a6d5-d618ce02a577)

**Comment by ImprovementSugar** [comment]
当我选择不同SQL语言的时候，无法正常渲染，报错：Warning: Attempted to synchronously unmount a root while React was already rendering. React cannot finish unmounting the root until the current render has completed, which may lead to a race condition.

![image](https://github.com/DTStack/monaco-sql-languages/assets/47029292/bf6da48b-4364-481e-9665-2938a6d3d876)

**Comment by liuxy0551** [comment]
我们本地的 pnpm 版本目前是 6.x，可以尝试一下 `pnpm@6.35.1`

**Comment by ImprovementSugar** [comment]
好的，应该是我版本太高

**Comment by HaydenOrz** [comment]
> 好的，应该是我版本太高

应该不是pnpm 的问题，这是website依赖的 molecule (Web IDE UI 框架) 的问题，这个warning 并不会影响到功能，我们尝试正在升级 molecule

https://github.com/DTStack/monaco-sql-languages/pull/97

**Comment by mortalYoung** [comment]
>  Error: Maximum call stack size exceeded 

这个原因是因为 Molecule 导致的，可以把 `@dtinsight/molecule` 的版本锁到 1.3.4，详见 [Molecule#887](https://github.com/DTStack/molecule/pull/887)

至于 warning 可以不用管，也是 Molecule 引起的，但是不会有影响，可以暂时先忽略

**Comment by ImprovementSugar** [comment]
好的，我我试下这个方法

**Comment by ImprovementSugar** [comment]
非常感谢，使用 @dtinsight/molecule  的1.3.4之后，程序运行正常
