### ISSUE TITLE
mysql下使用full join和case when语法会飘红提示错误

### ISSUE THREAD

**Issue by qinyouzhi** [DTStack/monaco-sql-languages#134]
1.当使用别名时full join语法会报错
如：
select * from db1.table1 as t1 full join

2.case when语法报错
如：
select
id,
case when age = 18 then '成年'
         when age = 60 then '老年' else '未知' end name

**Comment by liuxy0551** [comment]
1. mysql 中未找到 full join 语法的支持，查找资料发现可以通过 `LEFT JOIN` 和 `RIGHT JOIN` 组合去实现。  
2.

**Comment by liuxy0551** [comment]
1. mysql 中未找到 full join 语法的支持，查找资料发现可以通过 `LEFT JOIN` 和 `RIGHT JOIN` 组合去实现。  
2. 验证了下确实存在这个问题，当 `CASE` `WHEN` 之间没有 `case_value` 时，会有飘红提示，这需要由 [dt-sql-parser](https://github.com/DTStack/dt-sql-parser) 修复。稍晚些时候提供版本号。

**Comment by liuxy0551** [comment]
你可以使用 `monaco-sql-languages@0.12.2` ，在这个版本解决了 `CASE WHEN` 有飘红的问题，语法参考的是：https://dev.mysql.com/doc/refman/5.7/en/case.html

<img width="777" alt="image" src="https://github.com/DTStack/monaco-sql-languages/assets/34759874/27606356-670c-4db3-8fdf-6d0810438023">

**Comment by qinyouzhi** [comment]
非常感谢，还有个问题需要咨询一下：
我在用spark时语句where后不会提示column，在select后面可以正常提示，是设计就如此吗？

**Comment by liuxy0551** [comment]
> 非常感谢，还有个问题需要咨询一下： 我在用spark时语句where后不会提示column，在select后面可以正常提示，是设计就如此吗？

可以提供下示例语句吗

**Comment by qinyouzhi** [comment]
例如：
select column1, column2 from database.table1  这里的column1, column2会根据表字段进行提示

select * from database.table1 where column1  这里的column1在输入的时候没有提示，syntax只有function

**Comment by liuxy0551** [comment]
目前确实多个方言有这个问题，我们将在近期支持，后续可以在 https://github.com/DTStack/dt-sql-parser/issues/322 中查看进度。
