### ISSUE TITLE
现在按下空格就是唤起关键词提示,可不可以输入字母的时候才唤起提示 可以自己配置嘛?

### ISSUE THREAD

**Issue by yly1207** [DTStack/monaco-sql-languages#139]
![image](https://github.com/DTStack/dt-sql-parser/assets/82200570/d20866af-9cb3-4976-871f-307da160898a)

**Comment by HaydenOrz** [comment]
你可以通过 `setupLanguageFeatures` 方法来设置每一种语言的自动补全功能的触发方式，以flink为例：

https://microsoft.github.io/monaco-editor/docs.html#interfaces/languages.CompletionItemProvider.html#triggerCharacters

``` typescript
setupLanguageFeatures(LanguageIdEnum.FLINK, {
    completionItems: {
        enable: true, // 是否开启自动补全功能
        triggerCharacters: [' ', '.'], // 触发自动补全功能的输入字符
        completionService: //... ,
    }
});
```

**Comment by HaydenOrz** [comment]
Closed due to inactivity
