### ISSUE TITLE
Is the demo breaking? 

### ISSUE THREAD

**Issue by jchnxu** [DTStack/monaco-sql-languages#14]
main.js 404

After clicking parse there's an error.

Nothing valuable in the problems & output tab.

<img width="2555" alt="image" src="https://user-images.githubusercontent.com/4531670/189527493-4a011c3f-da70-4acc-b7a1-cd0e35c3e648.png">

**Comment by wewoor** [comment]
> 

Thanks for your feedback. The Problems has a bug.
