### ISSUE TITLE
hivesql的一些问题

### ISSUE THREAD

**Issue by wanyakun** [DTStack/monaco-sql-languages#143]
比如sql如下：
select a.id from dbname.table1 a left join dbname.table2 b on a.id = b.id and a.name = b.name

问题1. left join 和 and 关键字不高亮
问题2.  只有select后面能够收集到entities， on后面收集不到entities

**Comment by LuckyFBB** [comment]
关于高亮的问题，在最新的 playground 上，left join 和 and 与一些关键字一样都能够实现高亮。是否提供你对应的相关版本
<img width="775" alt="image" src="https://github.com/user-attachments/assets/636a253d-7502-46b5-837c-d06e119bfb13">

关于实体收集的问题，目前无法将查询的字段与查询条件中的字段区分开，还尚未实现收集

**Comment by wanyakun** [comment]
@LuckyFBB monaco-editor version: 0.44.0 monaco-sql-languages version: 0.12.2(antlr4ng-cli@1.0.7)(monaco-editor@0.44.0).
monaco-editor 自带的sql.contribution是可以高亮的。目前只能自己写个contribution，把monaco-editor自带的sql注册为hivesql。如下：
```ts
import { registerLanguage } from 'monaco-editor/esm/vs/basic-languages/_.contribution.js'
registerLanguage({
  id: 'hivesql',
  extensions: ['.hivesql'],
  aliases: ['HiveSQL', 'hive', 'Hive'],
  loader: () => import('monaco-editor/esm/vs/basic-languages/sql/sql')
})
```
关于实体收集，还没来得及看dt-sql-parser的代码，先问一下on后面是否可以收集token列表里（）括号区间内的table作为实体呢？

**Comment by HaydenOrz** [comment]
monaco-sql-languages 内部已经支持了SQL高亮功能，如果你的高亮功能失效，请按以下步骤检查：
1. 是否正常集成，相关集成文档 https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.md
2. 是否从 monaco-sql-languagues 中正确的引入了 hive sql 的contribution 文件，相关文档： https://github.com/DTStack/monaco-sql-languages?tab=readme-ov-file#usage
3. 检查在创建 moncao-editor 时，是否传入了正确的 language 配置，推荐使用monaco-sql-lanuages  导出的枚举 
    ```typescript
    import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
    import { LanguageIdEnum } from 'monaco-sql-languages';
    
    monaco.editor.create(document.getElementById('container'), {
        value: 'select * from tb_test',
        language: LanguageIdEnum.FLINK // languageId
    });
    ```
    
 如果上述检查完成后，仍存在问题，请创建一个最小的可复现demo，我们会尽快帮助你解决此问题。

**Comment by HaydenOrz** [comment]
@wanyakun 
> 关于实体收集，还没来得及看dt-sql-parser的代码，先问一下on后面是否可以收集token列表里（）括号区间内的table作为实体呢？

目前对于sql parser来说 JOIN ON 子句中，我们应该收集的是字段，但是此功能的实现上遇到一些困难，比如像 JOIN ON 、 where 、group by 等子句中，字段的收集很可能失效，这主要是因为 这些字段被嵌套在表达式中；

另外关于为什么 JOIN ON 、 where 、group by 等子句中只收集字段，而不是表名，原因与 https://github.com/DTStack/dt-sql-parser/issues/284 和 https://github.com/DTStack/dt-sql-parser/issues/189#issuecomment-1867405868  这里的讨论类似。

**Comment by wanyakun** [comment]
> @wanyakun monaco-sql-languages 内部已经支持了SQL高亮功能，如果你的高亮功能失效，请按以下步骤检查：
> 
> 1. 是否正常集成，相关集成文档 https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.md
> 2. 是否从 monaco-sql-languagues 中正确的引入了 hive sql 的contribution 文件，相关文档： https://github.com/DTStack/monaco-sql-languages?tab=readme-ov-file#usage
> 3. 检查在创建 moncao-editor 时，是否传入了正确的 language 配置，推荐使用monaco-sql-lanuages  导出的枚举
>    ```ts
>    import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
>    import { LanguageIdEnum } from 'monaco-sql-languages';
>    
>    monaco.editor.create(document.getElementById('container'), {
>        value: 'select * from tb_test',
>        language: LanguageIdEnum.HIVE// languageId
>    });
>    ```
> 
> 如果上述检查完成后，仍存在问题，请创建一个最小的可复现demo，我们会尽快帮助你解决此问题。

@HaydenOrz 问题出现在hive.ts文件中，tokenizer.root下的case块里。做如下更改，left jon和and就可以正常高亮显示了，应该操作类的关键字都有此问题。
`'@operators': TokenClassConsts.OPERATOR_KEYWORD`
改为：
`'@operators': TokenClassConsts.OPERATOR`

**Comment by HaydenOrz** [comment]
@wanyakun  
> @HaydenOrz 问题出现在hive.ts文件中，tokenizer.root下的case块里。做如下更改，left jon和and就可以正常高亮显示了，应该操作类的关键字都有此问题。 `'@operators': TokenClassConsts.OPERATOR_KEYWORD` 改为： `'@operators': TokenClassConsts.OPERATOR`

看起来是monaco theme 的问题，按照 monarch 文档所说，tokenClass 设置为 `TokenClassConsts.OPERATOR_KEYWORD` 和 `TokenClassConsts.OPERATOR` 不应该有这样的区别，因为实际上这两个枚举成员对应的值是:
<img width="540" alt="image" src="https://github.com/user-attachments/assets/dc587b02-b4fd-4b2f-ab73-d3a8170f864f">

可以看成`TokenClassConsts.OPERATOR_KEYWORD` 是 `TokenClassConsts.OPERATOR` 的子状态，也就是当 monaco 无法找到 TokenClassConsts.OPERATOR_KEYWORD 对应的类名时，会自动尝试看它的父状态有没有对应的类名， monarch 相关文档：https://microsoft.github.io/monaco-editor/monarch.html

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/ce22428d-8826-4d74-9714-c2dd5fc6744a">


这个问题还可能是因为你是自定义了 theme，亦或者是你所使用的 monaco-editor 版本的内置theme正好内置了 `operator.keyword` 这个 tokenClass 对应的样式；

对应的解决方法是: 你可以选择使用 monaco-sql-languages 提供的 theme ，相关文档在这里 https://github.com/DTStack/monaco-sql-languages/blob/main/README-zh_CN.md#monaco-theme

**Comment by wanyakun** [comment]
> @wanyakun
> 
> > @HaydenOrz 问题出现在hive.ts文件中，tokenizer.root下的case块里。做如下更改，left jon和and就可以正常高亮显示了，应该操作类的关键字都有此问题。 `'@operators': TokenClassConsts.OPERATOR_KEYWORD` 改为： `'@operators': TokenClassConsts.OPERATOR`
> 
> 看起来是monaco theme 的问题，按照 monarch 文档所说，tokenClass 设置为 `TokenClassConsts.OPERATOR_KEYWORD` 和 `TokenClassConsts.OPERATOR` 不应该有这样的区别，因为实际上这两个枚举成员对应的值是: <img alt="image" width="540" src="https://private-user-images.githubusercontent.com/58289241/365627836-dc587b02-b4fd-4b2f-ab73-d3a8170f864f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzcwMTgsIm5iZiI6MTcyNTkzNjcxOCwicGF0aCI6Ii81ODI4OTI0MS8zNjU2Mjc4MzYtZGM1ODdiMDItYjRmZC00YjJmLWFiNzMtZDNhODE3MGY4NjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAyNTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3M2M2OGVjMzYwOTliNjhmOGRlYmJkNDllNTE2NWQ2OWE4NmYxODFlMzZmZmU2MmY2ZDMzYzY3ZWNlODVlZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ejld9_oqarOCJqnds6BvIdEZ_X136QjWJauIDT7AJMo">
> 
> 可以看成`TokenClassConsts.OPERATOR_KEYWORD` 是 `TokenClassConsts.OPERATOR` 的子状态，也就是当 monaco 无法找到 TokenClassConsts.OPERATOR_KEYWORD 对应的类名时，会自动尝试看它的父状态有没有对应的类名， monarch 相关文档：https://microsoft.github.io/monaco-editor/monarch.html
> 
> <img alt="image" width="1393" src="https://private-user-images.githubusercontent.com/58289241/365629464-ce22428d-8826-4d74-9714-c2dd5fc6744a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzcwMTgsIm5iZiI6MTcyNTkzNjcxOCwicGF0aCI6Ii81ODI4OTI0MS8zNjU2Mjk0NjQtY2UyMjQyOGQtODgyNi00ZDc0LTk3MTQtYzJkZDVmYzY3NDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAyNTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZTk2Njc2ZjJlY2JjNjhmZWUyNDhlZTUzOWZlN2MzYTFkZjMyMjE4YzdhMWVkZWIwOTYzNzgzZDU1YzIxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-u4PzlISeW15iTjIPU8gJk_2T6CXQaUY-R9I2EZtAcM">
> 这个问题还可能是因为你是自定义了 theme，亦或者是你所使用的 monaco-editor 版本的内置theme正好内置了 `operator.keyword` 这个 tokenClass 对应的样式；
> 
> 对应的解决方法是: 你可以选择使用 monaco-sql-languages 提供的 theme ，相关文档在这里 https://github.com/DTStack/monaco-sql-languages/blob/main/README-zh_CN.md#monaco-theme

嗯嗯，测试一下monaco-sql-languages 提供的 theme，的确可以高亮，是主题的问题，我使用的是monaco-editor内置的主题，hive的tokenizer里的一些规则和主题不太兼容。
非常感谢。

**Comment by HaydenOrz** [comment]
@wanyakun 如果确认问题已解决，请关闭此 issue
