### ISSUE TITLE
Monaco Editor 动态注册 SQL 语言，集成语法高亮

### ISSUE THREAD

**Issue by wewoor** [DTStack/monaco-sql-languages#26]

**Comment by HaydenOrz** [comment]
flinkSql 高亮存在问题
+ 双引号的字符串字面量没有高亮
+ string 数据类型没有高亮
![image](https://github.com/DTStack/monaco-sql-languages/assets/58289241/be816048-6570-4415-939d-1f43a7ed8f13)

**Comment by HaydenOrz** [comment]
高亮 boolean 值
