### ISSUE TITLE
Proposal for create-react-app, monaco-editor  and sql languages bootstrap repo

### ISSUE THREAD

**Issue by shabalin** [DTStack/monaco-sql-languages#3]
Please check out the very basic demo app that aims to showcase `monaco-sql-languages` and also be a lightweight starting point for CRA-based projects with monaco editor and  `monaco-sql-languages` support configured
https://github.com/SlickSql/monaco-sql-languages-demo
Just in case you have any interest to collaborate!

**Comment by wewoor** [comment]
@shabalin Thanks for your suggestion,  I think this is a good idea, maybe you can submit a PR that adds a **CRA** case below `README.md` Example.
