### ISSUE TITLE
How to use in Umi

### ISSUE THREAD

**Issue by minbinHuang** [DTStack/monaco-sql-languages#33]
can not find the entry in umijs

**Comment by HaydenOrz** [comment]
In umi, you can use [MonacoEditorWebpackPlugin](https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin) . to import sql languages
1. Install MonacoEditorWebpackPlugin
```shell
npm i moanco-editor-webpack-plugin
```
2. Configure in the umi.ts
```typescript
import { defineConfig } from 'umi';
import MonacoWebpackPlugin from 'monaco-editor-webpack-plugin';

export default defineConfig({
  chainWebpack: (memo) => {
    memo.plugin('monaco-editor-webpack-plugin').use(MonacoWebpackPlugin, [
      {
        languages: [...],
        features: [...],
        customLanguages: [
          {
            label: 'flinksql',
            entry: 'monaco-sql-languages/out/esm/flinksql/flinksql.contribution',
            worker: {
              id: 'monaco-sql-languages/out/esm/flinksql/flinkSQLWorker',
              entry: 'monaco-sql-languages/out/esm/flinksql/flinksql.worker',
            },
          },
        ],
      },
    ]);
    return memo;
  },
});
```

And If you are using version `^0.12.0-beta`  of the monaco-sql-languages,  for flinkSQL, you need to import it in your code
```typescript
import { registerFlinkSQLLanguage } from 'monaco-sql-languages';
// register flink sql language
registerFlinkSQLLanguage();
```

Not required in other versions or using other SQL languages.

**Comment by minbinHuang** [comment]
import  registerFlinkSQLLanguage in global.tsx, and get an error that registerFlinkSQLLanguage  is not a function

**Comment by HaydenOrz** [comment]
> import registerFlinkSQLLanguage in global.tsx, and get an error that registerFlinkSQLLanguage is not a function

Please check if your monaco-sql-language version is equal to or greater than `0.12.0-beta`, if not ，`registerFlinkSQLLanguage` is  not needed.

**Comment by minbinHuang** [comment]
> > import registerFlinkSQLLanguage in global.tsx, and get an error that registerFlinkSQLLanguage is not a function
> 
> Please check if your monaco-sql-language version is equal to or greater than `0.12.0-beta`, if not ，`registerFlinkSQLLanguage` is not needed.

Thank you for your prompt reply, the registerFlinkSQLLanguage exported in the latest version did report an error, and it was successfully used after downgrading to version 0.11.0.

**Comment by HaydenOrz** [comment]
Thanks for your feedback too.

The 0.12.x version is currently in beta and may be unstable. But we didn't have the problem you mentioned when we tested it.

Version 0.12.x add auto-completion feature to flinksql language. With `registerFlinkSQLLanguage`, you can register custom completion services.

Could you please provide more information to help us fix possible issues on 0.12.x. For example, your code or project configuration information.

**Comment by minbinHuang** [comment]
a new project created by umi3.5.41, with react-monaco-editor 0.53.0, monaco-sql-languages 0.12.0-beta.1, monaco-editor-webpack-plugin 7.0.1
```
// index.js
import styles from './index.less';
import MonacoEditor from 'react-monaco-editor';
import { useState } from 'react';

export default function IndexPage() {
  const [code, setCode] = useState();
  return (
    <div>
      <MonacoEditor
        width="90vw"
        height="90vh"
        language="flinksql"
        value={code}
        theme="vs-dark"/>
    </div>
  );
}
```
```
//.umiirc.ts
import { defineConfig } from 'umi';
import MonacoWebpackPlugin from 'monaco-editor-webpack-plugin';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  fastRefresh: {},
  webpack5: {},
  chainWebpack: (memo) => {
    memo.plugin('monaco-editor-webpack-plugin').use(MonacoWebpackPlugin, [
      {
        customLanguages: [
          {
            label: 'flinksql',
            entry: 'monaco-sql-languages/out/esm/flinksql/flinksql.contribution',
            worker: {
              id: 'monaco-sql-languages/out/esm/flinksql/flinkSQLWorker',
              entry: 'monaco-sql-languages/out/esm/flinksql/flinksql.worker',
            },
          },
        ],
      },
    ]);
    return memo;
  },
});
```
another question is that i have not Define the MonacoEnvironment for worker file and import the language contribution before creating the editor by monaco-editor, just set language="flinksql" on MonacoEditor, and it work.

**Comment by HaydenOrz** [comment]
> another question is that i have not Define the MonacoEnvironment for worker file and import the language contribution before creating the editor by monaco-editor, just set language="flinksql" on MonacoEditor, and it work.

These are done by the [MonacoEditorWebpackPlugin](https://github.com/microsoft/monaco-editor/blob/main/webpack-plugin/README.md). including:
+ import contribution file of language
+ import worker of language
+ Inject global variables `MonacoEnvironment`

The current flinkSQL language features supported by monaco-sq-language are somewhat different, need to import the `registerFlinkSQLLanguage` manually.
This allows you to customize autocompletion by passing parameters to registerFlinkSQLLanguage.  If you don't customize autocompletion, only keywords will be automatically suggested

**Comment by minbinHuang** [comment]
> > another question is that i have not Define the MonacoEnvironment for worker file and import the language contribution before creating the editor by monaco-editor, just set language="flinksql" on MonacoEditor, and it work.
> 
> @minbinHuang These are done by the [MonacoEditorWebpackPlugin](https://github.com/microsoft/monaco-editor/blob/main/webpack-plugin/README.md). including:
> 
> * import contribution file of language
> * import worker of language
> * Inject global variables `MonacoEnvironment`
> 
> The current flinkSQL language features supported by monaco-sq-language are somewhat different, need to import the `registerFlinkSQLLanguage` manually. This allows you to customize autocompletion by passing parameters to registerFlinkSQLLanguage. If you don't customize autocompletion, only keywords will be automatically suggested

Get, thank you

**Comment by HaydenOrz** [comment]
This issue has been fixed. A new version will be released at a later date.
