### ISSUE TITLE
Vue3 + Vite4 + monaco-editor 加载 monaco-sql-languages package 报错

### ISSUE THREAD

**Issue by xinyufyj** [DTStack/monaco-sql-languages#39]
用 vue3 和 vite4 安装了 monaco-sql-languages, 但是启动项目之后， 控制台报错。
代码和错误如下：
![image](https://github.com/DTStack/monaco-sql-languages/assets/7018771/299bbaf4-efbf-4e4b-8d7e-3296c240e4bf)

![image](https://github.com/DTStack/monaco-sql-languages/assets/7018771/3d9564bf-9722-4b7a-acd6-01934d623bc5)

**Comment by HaydenOrz** [comment]
你可以参考
1. monaco-editor 官方文档  https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md#using-vite
2. vite 的 issue 中关于此问题的讨论 https://github.com/vitejs/vite/discussions/1791

**Comment by HaydenOrz** [comment]
另外本仓库的website 也是通过 vite4 构建，或许可以作为你的参考
+ [vite.config.js](https://github.com/DTStack/monaco-sql-languages/blob/main/website/vite.config.ts)
+ [ languageWorker.ts](https://github.com/DTStack/monaco-sql-languages/blob/main/website/src/languageWorker.ts)

**Comment by xinyufyj** [comment]
> 你可以参考
> 
> 1. monaco-editor 官方文档  https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md#using-vite
> 2. vite 的 issue 中关于此问题的讨论 [Import monaco-editor using Vite 2 vitejs/vite#1791](https://github.com/vitejs/vite/discussions/1791)

感谢回复，这些都参考过了，使用 monaco-editor 内置的 worker，如： json 和 JavaScript ，没有问题；但是使用 monaco-sql-languages 提供的 mysql 的 worker 就会报错；

**Comment by xinyufyj** [comment]
> 另外本仓库的website 也是通过 vite4 构建，或许可以作为你的参考
> 
> * [vite.config.js](https://github.com/DTStack/monaco-sql-languages/blob/main/website/vite.config.ts)
> * [ languageWorker.ts](https://github.com/DTStack/monaco-sql-languages/blob/main/website/src/languageWorker.ts)

website 中的代码也参考了，本地能正常启起来，看代码中用了 @dtinsight/molecule 这个 ide，但是直接用 mocano-editor 就会报错，不知道是我哪里没有配置对。

**Comment by HaydenOrz** [comment]
可以提供一下你的vite 配置文件吗

**Comment by xinyufyj** [comment]
没有额外的配置

**Comment by xinyufyj** [comment]
> 可以提供一下你的vite 配置文件吗

没有额外的 vite 配置

**Comment by zwight** [comment]
@xinyufyj 在你的vite配置文件中添加这个配置`assetsInclude: ['**/*.worker.js']`试试，把worker.js文件当作静态资源输出

**Comment by xinyufyj** [comment]
> @xinyufyj 在你的vite配置文件中添加这个配置`assetsInclude: ['**/*.worker.js?worker']`试试，把worker.js文件当作静态资源输出

感谢回复，试了下还是不行，跟 assetsInclude 配置应该没什么关系。

**Comment by xinyufyj** [comment]
> 可以提供一下你的vite 配置文件吗

@HaydenOrz 发现 monaco-sql-languages 的 worker 内部依赖了 dt-sql-parser，会有一些 nodejs 相关的 api，参考 website  中 vite.config.js 的配置，但是项目启动之后还是报错了，这是我的 vite 配置文件：

![image](https://github.com/DTStack/monaco-sql-languages/assets/7018771/a72ea50d-3466-4598-a916-49fdc921864f)

**Comment by mumiao** [comment]
> > @xinyufyj 在你的vite配置文件中添加这个配置`assetsInclude: ['**/*.worker.js?worker']`试试，把worker.js文件当作静态资源输出
> 
> 感谢回复，试了下还是不行，跟 assetsInclude 配置应该没什么关系。

本地构建一个minimal demo, 放到github repository，我们复现一下看看

**Comment by binbinecust** [comment]
我也遇到了一样的问题 好像也是用到了node的api 比如fs 和 dt-sql-parser，大佬你的问题解决了吗？

**Comment by binbinecust** [comment]
![image](https://github.com/DTStack/monaco-sql-languages/assets/23292261/8eff93f8-b09f-43bb-92ac-20b14b1e2663)

**Comment by binbinecust** [comment]
![image](https://github.com/DTStack/monaco-sql-languages/assets/23292261/810484f4-cd6d-40cc-b75b-22945c52e8dc)

**Comment by HaydenOrz** [comment]
关于在 vite 中集成的问题，关联 issue #87  以及 [vite issue#15359](https://github.com/vitejs/vite/issues/15359)

**Comment by HaydenOrz** [comment]
@xinyufyj  @binbinecust  现在 monaco-sql-languages 提供了一些[集成示例](https://github.com/DTStack/monaco-sql-languages/tree/main/samples)可以作为参考，另外更新了[集成文档](https://github.com/DTStack/monaco-sql-languages/blob/main/documents/integrate-esm.zh-CN.md)，以及[遇到集成问题如何解决](https://github.com/DTStack/monaco-sql-languages/blob/main/documents/problem-solving.zh-CN.md)的文档

但是很遗憾，目前在 vite 项目中集成仍然会有一些问题，我们会持续跟进集成相关问题

**Comment by HaydenOrz** [comment]
@xinyufyj @binbinecust   

monaco-sql-languages  0.12.0-beta.11  版本已发布：
https://www.npmjs.com/package/monaco-sql-languages/v/0.12.0-beta.11 

我们已经确认了此问题在改版本上修复，请安装该版本以修复此问题。
另外，该版本上有一些破坏性变更，如果升级后导致了项目异常，请查看最新的文档。

如果本问题不再活跃，将在一周内关闭。
