### ISSUE TITLE
在monaco-editor中无法使用hive-sql插件

### ISSUE THREAD

**Issue by ramtker** [DTStack/monaco-sql-languages#4]
使用monaco-sql- language 0.9.4，无法实现关键词提示、错误提示功能。
我这边用的monaco-editor版本是0.25.0

使用其他自带的如：html.worker，关键词提示都是正常的

**Comment by ramtker** [comment]
![Uploading 0D2F2967-75BD-423B-B1D9-0618502BC1B2.jpeg…]()

**Comment by ramtker** [comment]
直接用现在这个版本的dt-sql-parser，对语句做验证感觉也不太对
![Uploading 9727EAB7-0720-4159-A7B2-2BF56CD21D66.jpeg…]()

**Comment by wewoor** [comment]
@ramtker 图片都有问题

**Comment by wewoor** [comment]
> 使用monaco-sql- language 0.9.4，无法实现关键词提示、错误提示功能。 我这边用的monaco-editor版本是0.25.0
> 
> 使用其他自带的如：html.worker，关键词提示都是正常的

目前 [monaco-sql-languages](https://github.com/DTStack/monaco-sql-languages)   仅仅只支持了基础的语法校验功能，关键词暂时不支持。

`dt-sql-parser` v4 版本是基于 **antlr4** 的一个版本，目前处在 beta 状态，有些语法可能还没有覆盖

**Comment by LRH1993** [comment]
![21653025239_ pic](https://user-images.githubusercontent.com/19542787/169458698-26f39cab-b99d-4adb-8c94-9fa85cc27684.jpg)

**Comment by LRH1993** [comment]
![31653025240_ pic](https://user-images.githubusercontent.com/19542787/169458759-c0e341a5-8de3-4a32-bcd6-928aa1d94588.jpg)

**Comment by LRH1993** [comment]
@wewoor 图片重新上传了，麻烦看下

**Comment by wewoor** [comment]
> ![21653025239_ pic](https://user-images.githubusercontent.com/19542787/169458698-26f39cab-b99d-4adb-8c94-9fa85cc27684.jpg)

0.9.4 版本需要升级 monaco-editor 版本，推荐这个版本： 0.30.1

**Comment by ramtker** [comment]
使用0.30.1后，开发模式下可以正常提示
vue项目打包后，worker没有工作

[Image.jpeg][Image.jpeg]
使用的方式是
https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md
Option 2: Using plain webpack

是否还需要其他配置？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ziv ***@***.***>
发送时间: Friday, May 20, 2022 1:59:33 PM
收件人: DTStack/monaco-sql-languages ***@***.***>
抄送: ramtker ***@***.***>; Mention ***@***.***>
主题: Re: [DTStack/monaco-sql-languages] 在monaco-editor中无法使用hive-sql插件 (Issue #4)


[21653025239_ pic]<https://user-images.githubusercontent.com/19542787/169458698-26f39cab-b99d-4adb-8c94-9fa85cc27684.jpg>

0.9.4 版本需要升级 monaco-editor 版本，推荐这个版本： 0.30.1

―

**Comment by wewoor** [comment]
@ramtker 

浏览器控制台是否抛 EditorWorker 加载相关的异常？
1.  确认 worker output 有正确输出到**指定路径和名称**
2. 确保 getWorkerUrl 下加载的地址，与 webpack 输出的地址是对应的，例如：

```ts
self.MonacoEnvironment = {
	getWorkerUrl: function (moduleId, label) {
		if (label === 'hivesql') {
			return './hivesql.worker.js';
		}
		return './editor.worker.js';
	}
};
```
可以参考下我们这个配置：

https://github.com/DTStack/monaco-sql-languages/blob/main/scripts/webpack.base.js

https://github.com/DTStack/monaco-sql-languages/blob/main/web/app.js

**Comment by ramtker** [comment]
输入内容，控制台没有报错，worker都是加载成功的，这个配置我试试
MonacoWebpackPlugin 这个没有用到


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ziv ***@***.***>
发送时间: Wednesday, May 25, 2022 10:25:11 AM
收件人: DTStack/monaco-sql-languages ***@***.***>
抄送: ramtker ***@***.***>; Mention ***@***.***>
主题: Re: [DTStack/monaco-sql-languages] 在monaco-editor中无法使用hive-sql插件 (Issue #4)


@ramtker<https://github.com/ramtker>

浏览器控制台是否抛 EditorWorker 加载相关的异常？

  1.  确认 worker output 有正确输出到指定路径和名称
  2.  确保 getWorkerUrl 下加载的地址，与 webpack 输出的地址是对应的，例如：

self.MonacoEnvironment = {

        getWorkerUrl: function (moduleId, label) {

                if (label === 'hivesql') {

                        return './hivesql.worker.js';

                }

                return './editor.worker.js';

        }

};

可以参考下我们这个配置：

https://github.com/DTStack/monaco-sql-languages/blob/main/scripts/webpack.base.js

https://github.com/DTStack/monaco-sql-languages/blob/main/web/app.js

―

**Comment by ramtker** [comment]
问题已经解决
通过插件，MonacoWebpackPlugin，
属性customLanguages添加worker，打包后正常使用



获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: RAM TALK ***@***.***>
发送时间: Wednesday, May 25, 2022 10:32:21 AM
收件人: DTStack/monaco-sql-languages ***@***.***>; DTStack/monaco-sql-languages ***@***.***>
抄送: Mention ***@***.***>
主题: Re: [DTStack/monaco-sql-languages] 在monaco-editor中无法使用hive-sql插件 (Issue #4)

输入内容，控制台没有报错，worker都是加载成功的，这个配置我试试
MonacoWebpackPlugin 这个没有用到


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ziv ***@***.***>
发送时间: Wednesday, May 25, 2022 10:25:11 AM
收件人: DTStack/monaco-sql-languages ***@***.***>
抄送: ramtker ***@***.***>; Mention ***@***.***>
主题: Re: [DTStack/monaco-sql-languages] 在monaco-editor中无法使用hive-sql插件 (Issue #4)


@ramtker<https://github.com/ramtker>

浏览器控制台是否抛 EditorWorker 加载相关的异常？

  1.  确认 worker output 有正确输出到指定路径和名称
  2.  确保 getWorkerUrl 下加载的地址，与 webpack 输出的地址是对应的，例如：

self.MonacoEnvironment = {

        getWorkerUrl: function (moduleId, label) {

                if (label === 'hivesql') {

                        return './hivesql.worker.js';

                }

                return './editor.worker.js';

        }

};

可以参考下我们这个配置：

https://github.com/DTStack/monaco-sql-languages/blob/main/scripts/webpack.base.js

https://github.com/DTStack/monaco-sql-languages/blob/main/web/app.js

―
