### ISSUE TITLE
Module has no exports.

### ISSUE THREAD

**Issue by prmiyasaki** [DTStack/monaco-sql-languages#41]
I'm trying to incorporate monaco-sql-languages into existing project. I have followed the docs. When I run my app I get this error:

export 'default' (imported as 'FlinkSQLWorker') was not found in 'monaco-sql-languages/out/esm/flinksql/flinksql.worker?worker' (module has no exports)

**Comment by HaydenOrz** [comment]
Which version do you have installed?

And the current documentation is outdated and we are preparing to refactor it.

**Comment by HaydenOrz** [comment]
Inactive
