### ISSUE TITLE
[bug] pgsql syntax validation

### ISSUE THREAD

**Issue by karl-barkmann** [DTStack/monaco-sql-languages#42]
I've noticed that pgsql was supported by version 0.10.0，but it seems it is not working anymore, at least syntax validation is broken right now. 
I am using 0.11.0.

Tested on the website https://dtstack.github.io/monaco-sql-languages/ ,also not working .
However, the website https://salvoravida.github.io/monaco-sql-languages/ provided by the PR author can validate PostgreSQL syntax properly.

**Comment by HaydenOrz** [comment]
Hi, karl.

I have to admit that our SQL Parser does have some problems. We are planning to recheck all SQL Parser, but this will take quite a bit of time. The good news is that Flink SQL parser has been rechecked,
And you can see our progress in the [dt-sql-parser](https://github.com/DTStack/dt-sql-parser) project.

**Comment by HaydenOrz** [comment]
@karl-barkmann  
Sorry, this news may have come too late.

We have released a new version `0.12.0-beta.9`. In this release, PGSQL has updated the parser and supports autocompletion.

If you'd like, please give us feedback after trying the new version.
