### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/monaco-sql-languages#5]
如何运行得到这个界面
https://dtstack.github.io/monaco-sql-languages/

**Comment by BojunZhong** [comment]
![1](https://user-images.githubusercontent.com/102637083/173170231-d88a182f-b6e8-43f4-8bfe-8dd37c0d849f.png)
这里面只教我们如何安装，没有运行的指令

**Comment by wewoor** [comment]
> ![1](https://user-images.githubusercontent.com/102637083/173170231-d88a182f-b6e8-43f4-8bfe-8dd37c0d849f.png) 这里面只教我们如何安装，没有运行的指令

使用 `yarn dev `运行开发模式

**Comment by BojunZhong** [comment]
![ooo](https://user-images.githubusercontent.com/102637083/173295980-3051f918-8c51-4c98-b55b-4414819e9195.png)
这个没有显示网页啊，就显示一个这个，按照道理来说应该是显示这个
![1](https://user-images.githubusercontent.com/102637083/173296191-7bd05089-f23e-446c-8a42-f9d8114d8932.png)
的

**Comment by wewoor** [comment]
> ![ooo](https://user-images.githubusercontent.com/102637083/173295980-3051f918-8c51-4c98-b55b-4414819e9195.png) 这个没有显示网页啊，就显示一个这个，按照道理来说应该是显示这个 ![1](https://user-images.githubusercontent.com/102637083/173296191-7bd05089-f23e-446c-8a42-f9d8114d8932.png) 的

你这个似乎没有起来？Window 环境确实没试过，你看看日志

**Comment by BojunZhong** [comment]
那你是用哪个环境测试的？linux还是mac ios系统？还是其他的？

**Comment by wewoor** [comment]
> 那你是用哪个环境测试的？linux还是mac ios系统？还是其他的？

我们主要是 `Mac` 。建议你看看日志，先报的是什么问题

**Comment by BojunZhong** [comment]
就是显示，yarn dev后面就显示这个玩意儿。
![11](https://user-images.githubusercontent.com/102637083/173482538-0b849af3-47de-487c-beba-38a9ad833f2b.png)

**Comment by BojunZhong** [comment]
ok这些问题都解决了
