### ISSUE TITLE
Compatible with custom parameter syntax In BatchWorks

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/monaco-sql-languages#60]
e.g.  
+ `@@{componentParams}`  
+ `${sysParams}`

**Comment by liuxy0551** [comment]
1、`@@{componentParams}` 在组件中使用
<img width="1524" alt="image" src="https://github.com/DTStack/monaco-sql-languages/assets/34759874/696043a8-d770-4abf-aba9-752916652366">

2、`${taskParams}` 在任务中使用，有全局参数和自定义参数，全局参数粘贴到编辑器时可自动识别并添加到右侧任务参数
<img width="1533" alt="image" src="https://github.com/DTStack/monaco-sql-languages/assets/34759874/bfe87c89-5ec1-4d1f-a5d5-e15d48892d07">
