### ISSUE TITLE
如何添加一个自定义语言实现语法高亮

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/monaco-sql-languages#7]
![72d1c68c6db15be7cf6e62659d3f89f](https://user-images.githubusercontent.com/102637083/173319332-b299432c-d561-4ee9-9f91-ca5a8a85003c.png)
如果按照这个添加语言的方法去添加4个文件在里面，但是这些文件都是本地文件

依据taier的案例来看，taier导入是依据导入下载包的方法，这个方法是通过yarn指令下载monaco-sql-languages到node_modules中，这个与本地文件没什么关系把
![222 (2)](https://user-images.githubusercontent.com/102637083/173319923-08f76589-f6f0-4a98-a79a-5d71f9e2c40c.png)

**Comment by wewoor** [comment]
@BojunZhong `out` 目录下都是构建后的，你可以在项目里面直接添加语言，也可以像 monaco-sql-languages 一样独立仓库维护这些 language 文件。

**Comment by BojunZhong** [comment]
直接在项目里面添加的流程是什么？

**Comment by BojunZhong** [comment]
我已经成功导入语言包了
