### ISSUE TITLE
Integrating new pgsql parser 

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/monaco-sql-languages#78]
## TODO List
- [x] 支持 pgsql parser 自动补全功能
- [x] 高亮功能优化，包括关键字，内置函数，操作符，数据类型，各种字面量规则等等，对应的语言文件所有的规则和设置都需要重新检查
- [x] 更新 website

**Comment by zhi-zhi-zhi** [comment]
hello，看了下 @Cythia828 已经进了相关 PR，请问计划下个包啥时候发呀？

**Comment by Cythia828** [comment]
hi，感谢您的关注！
目前正在最后确认阶段，有些细节正在完善，近一两周左右就会发包了，敬请期待
