### ISSUE TITLE
可考虑支持结合Ace editor 使用吗？

### ISSUE THREAD

**Issue by melin** [DTStack/monaco-sql-languages#80]
可考虑支持结合Ace editor 使用吗？ https://github.com/ajaxorg/ace

**Comment by HaydenOrz** [comment]
目前我们在 dt-sql-parser 上和 monaco-sql-languages 上还有大量的开发计划，暂时没有精力考虑结合 Ace editor。 如果你有兴趣，可以自行结合 [dt-sql-parser](https://github.com/DTStack/dt-sql-parser) 开发。

**Comment by HaydenOrz** [comment]
> 我们现在系统是基于jquery的，dt-sql-parser 怎么结合jquery 使用？ 能否补充这方面的使用文档？
你们的项目没有 bundler 吗？ 比如 webpack，vite 或者 rollup 之类的

**Comment by HaydenOrz** [comment]
抱歉，目前并不直接支持在原生环境中使用，dt-sql-parser 和 monaco-sql-languges 都需要 bundler 编译转换

**Comment by HaydenOrz** [comment]
#18
