### ISSUE TITLE
Monaco CompletionItem documentation not showing?

### ISSUE THREAD

**Issue by Samrose-Ahmed** [DTStack/monaco-sql-languages#81]
Has anyone been able to get Monaco completion documentation to show? I am returning the `documentation` property in my `CompletionItem` from my `completionService`, but I don't see it render. The `label` and `detail` show correctly. I am not sure why, am trying to rule out if it is caused by this package or some other setting.

Documentation should look like the following btw (the right window)

![image](https://github.com/DTStack/monaco-sql-languages/assets/9027301/f4e107c5-bb2f-419d-b38d-8a6e9460d0a1)

**Comment by HaydenOrz** [comment]
We are unable to reproduce the issue.
![image](https://github.com/DTStack/monaco-sql-languages/assets/58289241/41061451-96f4-48c8-a196-6dec4aa28bb0)

monaco-sql-languages doesn't do anything with the document in CompletionItem.

**Comment by HaydenOrz** [comment]
Is this problem solved？I'm happy to provide as much support as I can.

 If this problem has been resolved or it is confirmed that it is not a monaco-sql-languages bug, please close the issue. 
 
 Or we'll close it in three days because it's already inactive,
