### ISSUE TITLE
support monaco.languages.CompletionList.incomplete

### ISSUE THREAD

**Issue by Kijin-Seija** [DTStack/monaco-sql-languages#99]
I need to trigger the 'incomplete' logic in the return value of Monaco Editor's provideCompletionItems. Currently, it seems that only 'suggestion' is exported. If it doesn't interfere with your normal plans, I can provide a pull request. My fork: https://github.com/Kijin-Seija/monaco-sql-languages

---

我需要触发Monaco Editor ```provideCompletionItems``` 返回值中的 incomplete 逻辑，我看现在只导出了suggestion。
如果不影响你们正常计划的话，我可以提供pr，我的fork: https://github.com/Kijin-Seija/monaco-sql-languages

![image](https://github.com/DTStack/monaco-sql-languages/assets/27846243/76064076-14d8-4650-97f3-1f4b5545195d)

![image](https://github.com/DTStack/monaco-sql-languages/assets/27846243/e650d078-5bdc-4099-b7b4-a3329217218b)

**Comment by HaydenOrz** [comment]
> 我需要触发Monaco Editor `provideCompletionItems` 返回值中的 incomplete 逻辑，我看现在只导出了suggestion。 如果不影响你们正常计划的话，我可以提供pr，我的fork: https://github.com/Kijin-Seija/monaco-sql-languages

非常欢迎 PR，感谢！

**Comment by Kijin-Seija** [comment]
修改了变量名拼写错误，重新提交

**Comment by HaydenOrz** [comment]
@Kijin-Seija  hello, 再次感谢你的 PR，我针对此问题，发起了新的 PR，可以一起 review 下

**Comment by Kijin-Seija** [comment]
> @Kijin-Seija hello, 再次感谢你的 PR，我针对此问题，发起了新的 PR，可以一起 review 下

我已经review了，辛苦你这边的优化工作
